### ISSUE TITLE
Error: Download failed: server returned 404

### ISSUE THREAD

**Issue by mispay-bnpl** [gboutte/nestjs-pdf#3]
Hey!

When I try to start my NestJS app, it complains cannot download the chrome. 

```sh
est] 59865  - 02/16/2024, 9:52:18 PM     LOG [RouterExplorer] Mapped {/document/:docId, PUT} route +1ms
[Nest] 59865  - 02/16/2024, 9:52:18 PM     LOG [NestApplication] Nest application successfully started +2ms

........./node_modules/@puppeteer/browsers/src/httpUtil.ts:68
      response(res);
      ^
Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-x64/chrome-headless-shell-mac-x64.zip
    at ...../node_modules/@puppeteer/browsers/src/httpUtil.ts:98:23
    at ClientRequest.requestCallback (..../node_modules/@puppeteer/browsers/src/httpUtil.ts:68:7)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
Waiting for the debugger to disconnect...
```

Here is my config

```ts
@Module({
  imports: [
    ConfigModule.forRoot({
      validationSchema: envConfigSchema,
      load: [appConfig],
    }),
    PdfModule.forRoot({
      pdfOptions: {
        format: 'A4',
        margin: {
          top: '20px',
          bottom: '20px',
          left: '20px',
          right: '20px',
        },
      },
      browser: Browser.CHROMEHEADLESSSHELL,
      browserTag: BrowserTag.STABLE,
      useLockedBrowser: true,
      chromiumRevision: '121.0.6167.184',
      hbsOptions: {
        templateDirectory: 'templates',
        compileOptions: {},
        templateOptions: {},
      },
    }),
  ],
  controllers: [DocumentController],
...
```

do you have any idea?

**Comment by gboutte** [comment]
Hi !
I tried to run your exemple and I had the same error.

To download the browser I'm using the `@puppeteer/browsers` library, and I don't know why but it seem that `CHROMEHEADLESSSHELL` with `STABLE` is giving this error. 

I tried to change `BrowserTag.STABLE` to `BrowserTag.LATEST` and the installation is now working,  that's not perfect but it could work for you.

Also the parameter `chromiumRevision` is no longer used, so you don't need to define it.

**Comment by gboutte** [comment]
I searched more and found out that the download urls provided by google are not the same as the one used by puppeteer: https://googlechromelabs.github.io/chrome-for-testing/#stable

I published a new version to add a new parameter, that should allow you to define the base url of the download.
```ts
PdfModule.forRoot({
      useLockedBrowser: true,
      browser: Browser.CHROMEHEADLESSSHELL,
      browserTag: BrowserTag.STABLE,
      browserInstallBaseUrl:
        'https://storage.googleapis.com/chrome-for-testing-public',
}),
```

This should fix you problem.

**Comment by mispay-bnpl** [comment]
Thanks for the quick response and great fix. I tried with the `LATEST` tag but it hasn't worked either but the new param saved the day.

thanks a lot 🙏🏻
